[package]
name = "posture-notifier"
version = "0.1.0"
authors = ["Ragnyll <ragnyll@gallowzhumour.dev>"]
edition = "2021"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[dependencies]
dirs = "4.0.0"
notify-rust = "4.5"
strum = "0.24"
strum_macros = "0.24"

